WITH ins_lpbasic_tmp AS (
--非自然人集團客戶基本資料
SELECT
    CAST(DA501.CUSTOMER_ID AS STRING) AS ID_NO, --統一編號
    'INS' AS SOURCE, --來源子公司別
    CAST(DA501.CUSTOMER_NAME AS STRING) AS C_FULLNAME, --中文姓名
    CAST(DA501.CUSTOMER_ENGLISH_NAME AS STRING) AS E_FULLNAME, --英文姓名
    CAST(DA501.ENTITY_SETTIME AS STRING) AS BUILD_DATE, --設立日期*
    CAST(DA501.ENTITY_REG_CTYCODE AS STRING) AS COUNTRY, --註冊國別*
    CAST(REGISTERED_ADDR.ADDRESS AS STRING) AS REGISTERED_ADDR, --註冊地址
    CAST(DA501.OCCU_TYPE1_CODE AS STRING) AS INDUSTRY_TYPE1,--行職業大項
    CAST(DA501.OCCU_TYPE3_CODE AS STRING) AS INDUSTRY_TYPE2,--行職業小項
    '' AS ESTATE_SOURCE,--資金來源
    CAST(INVEST_SOURCE.PAY_SOURCE AS STRING) AS INVEST_SOURCE,--資產來源
    '' AS YEAR_PROFIT,--年營業額
    CAST(ANNUAL_INCOME.MIN_YEAR_INCOME AS STRING) AS PAID_UP_CAPITAL,--實收資本額 -- 還有這個欄位嗎？
    '' AS PRODUCT_CUB,--建立業務目的
    '' AS OWNER_STRUCT,--股權結構三層以上
    CAST(DA501.BEARER_SHARES_STATUS AS STRING) AS IS_BEARER_SHARES,--無記名股份或由無記名股份公司持股*
    '' AS IS_HIDE_OWNER,--具有隱名股東、Nominee之情況
    CAST(CURRENT_DATE() AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    CAST('2024-08-16' AS TIMESTAMP_NTZ) AS CREATE_DATE--這裡要改成首次建立的日期
FROM (SELECT * FROM raw_clean.ins.DTATA501 WHERE DATE_FORMAT(DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date' ) AS DA501

---------- 註冊地址----------
LEFT JOIN (
    SELECT * FROM (
        SELECT ID, ADDRESS, ROW_NUMBER() OVER (PARTITION BY ID ORDER BY CREATE_DATE DESC) sn FROM (
            SELECT CUSTOMER_ID AS ID, ADDRESS, CREATE_DATE
            FROM raw_clean.ins.DTABP005
            WHERE ADDRESS_KIND = '1'
            AND ADDRESS <> ''
            AND ADDRESS IS NOT NULL
            AND DATE_FORMAT(DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
        ) r
    ) R
    WHERE R.sn = 1
) REGISTERED_ADDR
ON DA501.CUSTOMER_ID = REGISTERED_ADDR.ID

---------- 資產來源----------
LEFT JOIN (
    SELECT * FROM (
        SELECT ID, PAY_SOURCE, ROW_NUMBER() OVER (PARTITION BY ID ORDER BY CREATE_DATE DESC) sn FROM (
            SELECT DA501.CUSTOMER_ID AS ID, DP707.PAY_SOURCE, DP707.CREATE_DATE_TIME AS CREATE_DATE
            FROM raw_clean.ins.DTPAP707 DP707
            LEFT JOIN raw_clean.ins.DTATA501 DA501
            ON DP707.CONTRACT_NO = DA501.CONTRACT_NO
            AND DATE_FORMAT(DP707.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            AND DATE_FORMAT(DA501.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            WHERE DP707.PAY_SOURCE <> ''
            AND DP707.PAY_SOURCE IS NOT NULL
            UNION ALL
            SELECT DA501.CUSTOMER_ID AS ID, DP611.PREMIUM_SOURCE AS PAY_SOURCE, DP611.CREATE_DATE AS CREATE_DATE
            FROM raw_clean.ins.DTABP611 DP611
            LEFT JOIN raw_clean.ins.DTATA501 DA501
            ON DP611.CONTRACT_NO = DA501.CONTRACT_NO
            AND DATE_FORMAT(DP611.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            AND DATE_FORMAT(DA501.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            WHERE DP611.PREMIUM_SOURCE <> ''
            AND DP611.PREMIUM_SOURCE IS NOT NULL
        ) r
    ) R
    WHERE R.sn = 1
) INVEST_SOURCE
ON DA501.CUSTOMER_ID = INVEST_SOURCE.ID

----------實收資本額----------
LEFT JOIN (
    SELECT * FROM (
        SELECT ID, MIN_YEAR_INCOME, ROW_NUMBER() OVER (PARTITION BY ID ORDER BY CREATE_DATE DESC) sn FROM (
            SELECT DA501.CUSTOMER_ID AS ID, DP707.MIN_YEAR_INCOME, DP707.CREATE_DATE_TIME AS CREATE_DATE
            FROM raw_clean.ins.DTPAP707 DP707
            LEFT JOIN raw_clean.ins.DTATA501 DA501
            ON DP707.CONTRACT_NO = DA501.CONTRACT_NO
            AND DATE_FORMAT(DP707.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            AND DATE_FORMAT(DA501.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            WHERE DP707.MIN_YEAR_INCOME <> ''
            AND DP707.MIN_YEAR_INCOME IS NOT NULL
            UNION ALL
            SELECT DA501.CUSTOMER_ID AS ID, DP611.MIN_YEAR_INCOME, DP611.CREATE_DATE AS CREATE_DATE
            FROM raw_clean.ins.DTABP611 DP611
            LEFT JOIN raw_clean.ins.DTATA501 DA501
            ON DP611.CONTRACT_NO = DA501.CONTRACT_NO
            AND DATE_FORMAT(DP611.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            AND DATE_FORMAT(DA501.DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date'
            WHERE DP611.MIN_YEAR_INCOME <> ''
            AND DP611.MIN_YEAR_INCOME IS NOT NULL
        ) r
    ) R
    WHERE R.sn = 1
) ANNUAL_INCOME
ON DA501.CUSTOMER_ID = ANNUAL_INCOME.ID
)