WITH ins_lprisk_tmp AS (
--非自然人集團客戶風險資料
SELECT
    CAST(DA501.CUSTOMER_ID AS STRING) AS ID_NO, --統一編號
    'INS' AS SOURCE, --來源子公司別
    CAST(DA501.RISK_LEVEL AS STRING) AS RISK_LEVEL, --客戶風險評級
    CAST(DA501.RISK_LEVEL_UPDATE AS STRING) AS RISK_MODIFY_DATE, --風險評級最後異動日期
    CAST(0 AS STRING) AS IS_CFH_PROHIBITEDLIST,
    CAST(0 AS STRING) AS IS_CFH_SIP,
    CAST(DA501.SAN AS STRING) AS IS_SAN, --制裁名單
    CAST(DA501.MNY_ERR AS STRING) AS IS_PROHIBITEDLIST, --子公司禁止名單
    CAST(DA501.SIP AS STRING) AS IS_SIP, --子公司關注名單
    CAST(DA501.AM AS STRING) AS IS_AME, --子公司負面新聞
    CAST(DA501.PEP AS STRING) AS IS_PEP, --重要政治人物名單(PEP)
    CAST(DA501.RCA AS STRING) AS IS_RCA, --重要政治人物名單_密切關係人名單(RCA)
    CAST(DG011.DATA1 AS STRING) AS INDUSTRY_RISK, --行職業風險等級
    CAST(DP001.PRODUCT_POLICY_CODE AS STRING) AS PROD_CXL_APC, --產品類別
    CAST(DA501.RISK_SCORE_PROD AS STRING) AS PROD_RISK_CXL_APC, --產品風險評級
    CAST(DG012.RISK_LEVEL AS STRING) AS COUNTRY_RISK, --國家(地域)風險評級
    CAST(CURRENT_DATE() AS TIMESTAMP_NTZ) AS LAST_MODIFIED_DATE,
    CAST('2024-08-16' AS TIMESTAMP_NTZ) AS CREATE_DATE --這裡要改成首次建立的日期
FROM (SELECT * FROM raw_clean.ins.DTATA501 WHERE DATE_FORMAT(DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date') AS DA501
----------行職業風險等級---------
LEFT JOIN (SELECT * FROM raw_clean.ins.DTAGG011 WHERE DATE_FORMAT(DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date') AS DG011
    ON DA501.RISK_INDUSTRY_CODE = DG011.CODE
----------產品風險評級---------
LEFT JOIN (SELECT * FROM raw_clean.ins.DTABP001 WHERE DATE_FORMAT(DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date') AS DP001
    ON DA501.CONTRACT_NO = DP001.CONTRACT_NO
----------國家(地域)風險評級---------
LEFT JOIN (SELECT * FROM raw_clean.ins.DTAGG012 WHERE DATE_FORMAT(DBC_BUSINESS_DATE, 'yyyy-MM-dd') = '$business_date') AS DG012
    ON DA501.OCR_COUNTRY_CODE = DG012.COUNTRY_CODE
)
